sudo: false

language: node_js

node_js:
  - 8.4

cache:
  directories:
    - node_modules

after_success:
  - yarn add codecov.io coveralls
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

script:
  - yarn test:ci
  - yarn lint
  - yarn build
