sudo: true

language: node_js

node_js:
  - 8.4

cache:
  directories:
    - node_modules

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull

after_success:
  - yarn add codecov.io coveralls --no-save
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - gem install github_changelog_generator
  - github_changelog_generator --token $GITHUB_TOKEN --date-format %y/%m/%d
  - git add CHANGELOG.md
  - git commit -m "Updated change log"
  - git push "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG" $TRAVIS_BRANCH

script:
  - yarn lint
  - yarn build
  - yarn test:coverage

deploy:
  - provider: pages
    name: Github Pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: script
    script: yarn release:ci
    on:
      tags: true
